name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Generate production .env file
        run: |
          echo "DEBUG=false" > .env
          echo "CORS_ORIGINS=*" >> .env
          echo "SECRET_KEY=$(openssl rand -hex 32)" >> .env
          echo "CSRF_SECRET_KEY=$(openssl rand -hex 32)" >> .env
          echo "DATABASE_URL=sqlite+aiosqlite:////app/filaman.db" >> .env
          echo "Generated .env file for build:"
          cat .env

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/fire-devils/filaman-system:latest
            ghcr.io/fire-devils/filaman-system:${{ gitea.sha }}
          cache-from: type=registry,ref=ghcr.io/fire-devils/filaman-system:buildcache
          cache-to: type=registry,ref=ghcr.io/fire-devils/filaman-system:buildcache,mode=max