"""add_device_code_to_device

Revision ID: 05f3346e9f36
Revises: d4e5f6a7b8c9
Create Date: 2026-02-18 12:32:35.020740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f3346e9f36'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_code', sa.String(length=6), nullable=True))
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_column('devices', 'device_code')
    # ### end Alembic commands ###
