"""Initial tables

Revision ID: 4b9f107a3faf
Revises: 
Create Date: 2026-02-13 22:37:01.879108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9f107a3faf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'hex_code', name='uq_colors_name_hex')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('spool_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('filaments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('material_subgroup', sa.String(length=100), nullable=True),
    sa.Column('diameter_mm', sa.Float(), nullable=False),
    sa.Column('manufacturer_color_name', sa.String(length=255), nullable=True),
    sa.Column('finish_type', sa.String(length=50), nullable=True),
    sa.Column('raw_material_weight_g', sa.Float(), nullable=True),
    sa.Column('default_spool_weight_g', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('shop_url', sa.String(length=500), nullable=True),
    sa.Column('density_g_cm3', sa.Float(), nullable=True),
    sa.Column('color_mode', sa.String(length=20), nullable=False),
    sa.Column('multi_color_style', sa.String(length=20), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('provider_email_verified', sa.Boolean(), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_oauth_provider_subject')
    )
    op.create_table('printers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('driver_key', sa.String(length=100), nullable=False),
    sa.Column('driver_config', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filament_colors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('display_name_override', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['filament_id'], ['filaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filament_id', 'position', name='uq_filament_colors_filament_position')
    )
    op.create_table('filament_printer_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('is_default_for_printer', sa.Boolean(), nullable=False),
    sa.Column('nozzle_diameter_mm', sa.Float(), nullable=True),
    sa.Column('extruder_type', sa.String(length=50), nullable=True),
    sa.Column('nozzle_temp_c', sa.Integer(), nullable=True),
    sa.Column('bed_temp_c', sa.Integer(), nullable=True),
    sa.Column('chamber_temp_c', sa.Integer(), nullable=True),
    sa.Column('print_speed_mm_s', sa.Integer(), nullable=True),
    sa.Column('travel_speed_mm_s', sa.Integer(), nullable=True),
    sa.Column('first_layer_speed_mm_s', sa.Integer(), nullable=True),
    sa.Column('max_volumetric_flow_mm3_s', sa.Float(), nullable=True),
    sa.Column('flowrate_percent', sa.Integer(), nullable=True),
    sa.Column('extrusion_multiplier', sa.Float(), nullable=True),
    sa.Column('pressure_advance_k', sa.Float(), nullable=True),
    sa.Column('linear_advance_k', sa.Float(), nullable=True),
    sa.Column('retraction_mm', sa.Float(), nullable=True),
    sa.Column('retraction_speed_mm_s', sa.Integer(), nullable=True),
    sa.Column('deretraction_speed_mm_s', sa.Integer(), nullable=True),
    sa.Column('retraction_extra_prime_mm3', sa.Float(), nullable=True),
    sa.Column('fan_percent_min', sa.Integer(), nullable=True),
    sa.Column('fan_percent_max', sa.Integer(), nullable=True),
    sa.Column('fan_first_layer_percent', sa.Integer(), nullable=True),
    sa.Column('z_hop_mm', sa.Float(), nullable=True),
    sa.Column('z_hop_only_when_retracting', sa.Boolean(), nullable=True),
    sa.Column('bridge_flow_percent', sa.Integer(), nullable=True),
    sa.Column('bridge_fan_percent', sa.Integer(), nullable=True),
    sa.Column('material_notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filament_id'], ['filaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filament_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filament_id'], ['filaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filament_id', 'user_id', name='uq_filament_ratings_filament_user')
    )
    op.create_table('printer_ams_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('ams_unit_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('slots_total', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printer_id', 'ams_unit_no', name='uq_printer_ams_units_printer_unit')
    )
    op.create_table('spools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('rfid_uid', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('stocked_in_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('initial_total_weight_g', sa.Float(), nullable=True),
    sa.Column('empty_spool_weight_g', sa.Float(), nullable=True),
    sa.Column('remaining_weight_g', sa.Float(), nullable=True),
    sa.Column('spool_outer_diameter_mm', sa.Float(), nullable=True),
    sa.Column('spool_width_mm', sa.Float(), nullable=True),
    sa.Column('low_weight_threshold_g', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filament_id'], ['filaments.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['spool_statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('rfid_uid')
    )
    op.create_table('printer_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('is_ams_slot', sa.Boolean(), nullable=False),
    sa.Column('ams_unit_id', sa.Integer(), nullable=True),
    sa.Column('slot_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ams_unit_id'], ['printer_ams_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printer_id', 'is_ams_slot', 'ams_unit_id', 'slot_no', name='uq_printer_slots_unique')
    )
    op.create_table('spool_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spool_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('delta_weight_g', sa.Float(), nullable=True),
    sa.Column('measured_weight_g', sa.Float(), nullable=True),
    sa.Column('from_status_id', sa.Integer(), nullable=True),
    sa.Column('to_status_id', sa.Integer(), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['from_status_id'], ['spool_statuses.id'], ),
    sa.ForeignKeyConstraint(['spool_id'], ['spools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['to_status_id'], ['spool_statuses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('printer_slot_assignments',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('spool_id', sa.Integer(), nullable=True),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('rfid_uid', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['printer_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spool_id'], ['spools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('printer_slot_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=False),
    sa.Column('spool_id', sa.Integer(), nullable=True),
    sa.Column('rfid_uid', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['printer_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spool_id'], ['spools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printer_slot_events')
    op.drop_table('printer_slot_assignments')
    op.drop_table('spool_events')
    op.drop_table('printer_slots')
    op.drop_table('spools')
    op.drop_table('printer_ams_units')
    op.drop_table('filament_ratings')
    op.drop_table('filament_printer_profiles')
    op.drop_table('filament_colors')
    op.drop_table('user_sessions')
    op.drop_table('user_roles')
    op.drop_table('user_permissions')
    op.drop_table('user_api_keys')
    op.drop_table('role_permissions')
    op.drop_table('printers')
    op.drop_table('oauth_identities')
    op.drop_table('filaments')
    op.drop_table('users')
    op.drop_table('spool_statuses')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('manufacturers')
    op.drop_table('locations')
    op.drop_table('devices')
    op.drop_table('colors')
    # ### end Alembic commands ###
