"""add ip_address and last_seen_at to device

Revision ID: c5d8f74c07af
Revises: 05f3346e9f36
Create Date: 2026-02-18 16:17:59.793309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d8f74c07af'
down_revision: Union[str, Sequence[str], None] = '05f3346e9f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('ip_address', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'ip_address')
    op.drop_column('devices', 'last_seen_at')
    # ### end Alembic commands ###
